history ls: fix '--format' flag to accept go templates
Before this PR, attempting to use a format template would always fail;

```bash
docker buildx history ls --no-trunc --format 'table {{.Status}}\t{{.NumTotalSteps}}\t{{.Duration}}\t{{.Name}}'
ERROR: template parsing error: template: :1:14: executing "" at <.NumTotalSteps>: can't evaluate field NumTotalSteps in type *history.lsContext
```

With this PR, formatting works (mostly); the formatting templates don't
match the JSON response (which can be confusing), and not all fields have
a table defined (which can result in `<no value>` used).

```bash
docker buildx history ls --no-trunc --format 'table {{.Status}}\t{{.NumTotalSteps}}\t{{.Duration}}\t{{.Name}}'
STATUS      <no value>   DURATION   NAME
Completed   16           17.1s      buildx (binaries)
Completed   12           19.9s      buildkit/hack/dockerfiles/vendor.Dockerfile (update)
Completed   123          28.7s      docker (dev-base)
Completed   26           7.9s
Completed   12           2m 41s     cli/dockerfiles/Dockerfile.vendor (update)
```

Or a slightly more adventurous;

```bash
docker buildx history ls --no-trunc --format '{{printf "{\"status\":%s,\"steps\":%s,\"duration\":%s,\"name\":%s}" (json .Status) (json .NumTotalSteps) (json .Duration) (json .Name)}}'
{"status":"Completed","steps":16,"duration":"17.1s","name":"buildx (binaries)"}
{"status":"Completed","steps":12,"duration":"19.9s","name":"buildkit/hack/dockerfiles/vendor.Dockerfile (update)"}
{"status":"Completed","steps":123,"duration":"28.7s","name":"docker (dev-base)"}
{"status":"Completed","steps":26,"duration":"7.9s","name":""}
{"status":"Completed","steps":12,"duration":"2m 41s","name":"cli/dockerfiles/Dockerfile.vendor (update)"}
{"status":"Error","steps":11,"duration":"3m 14s","name":"cli/dockerfiles/Dockerfile.vendor (update)"}
```

The flag description has been updated to align with other `--format` flags;

```bash
docker buildx history ls --help
Usage:  docker buildx history ls [OPTIONS]

List build records

Options:
      --builder string       Override the configured builder instance
  -D, --debug                Enable debug logging
      --filter stringArray   Provide filter values (e.g., "status=error")
      --format string        Format output using a custom template:
                             'table':            Print output in table format with column headers (default)
                             'table TEMPLATE':   Print output in table format using the given Go template
                             'json':             Print in JSON format
                             'TEMPLATE':         Print output using the given Go template.
                             Refer to https://docs.docker.com/go/formatting/ for more information about
                             formatting output with templates (default "table")
      --local                List records for current repository only
      --no-trunc             Don't truncate output
```

Signed-off-by: Sebastiaan van Stijn <github@gone.nl>